In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/numeric_pattern.csv")

clean_df = df.copy()

In [6]:
# Replacing null values with median

for column in clean_df.columns:
    
    if clean_df[column].isnull().sum() > 0:
        
        median_value = clean_df[column].median()
        
        clean_df[column] = clean_df[column].fillna(median_value)

print(clean_df.isnull().sum())

Feature_1     0
Feature_2     0
Feature_3     0
Feature_4     0
Feature_5     0
Feature_6     0
Feature_7     0
Feature_8     0
Feature_9     0
Feature_10    0
Target        0
dtype: int64

In [ ]:
# Remove duplicated values

clean_df.duplicated().sum()

np.int64(74)

In [ ]:
clean_df = clean_df.drop_duplicates()
clean_df.duplicated().sum()

np.int64(0)

In [ ]:
# Removing outliers

feature_columns = [
    column
    for column in clean_df.columns
    if column != "Target"
]

In [15]:
outlier_summary = []

for column in feature_columns:

    Q1 = clean_df[column].quantile(0.25)
    Q3 = clean_df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = clean_df[
        (clean_df[column] < lower_bound)
        | (clean_df[column] > upper_bound)
    ]

    outlier_summary.append({
        "Feature": column,
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "Lower Bound": lower_bound,
        "Upper Bound": upper_bound,
        "Outlier Count": len(outliers)
    })

outlier_summary = pd.DataFrame(outlier_summary)

display(outlier_summary)

,Feature,Q1,Q3,IQR,Lower Bound,Upper Bound,Outlier Count
0,Feature_1,39.645056,59.520660,19.875603,9.831651,89.334065,0
1,Feature_2,25.059854,73.987390,48.927537,-48.331452,147.378696,0
2,Feature_3,83.138876,116.651705,33.512829,32.869632,166.920949,0
3,Feature_4,30.008008,70.422913,40.414904,-30.614348,131.045269,0
4,Feature_5,-0.630097,0.662379,1.292476,-2.568811,2.601094,0
5,Feature_6,5.901671,28.296328,22.394657,-27.690315,61.888314,0
6,Feature_7,432.847581,568.338542,135.490960,229.611141,771.574982,0
7,Feature_8,3.284164,7.826914,4.542750,-3.529961,14.641039,0
8,Feature_9,21.653817,28.233488,6.579671,11.784311,38.102995,0
9,Feature_10,-2.478879,2.468120,4.946999,-9.899378,9.888619,0

In [11]:
for column in feature_columns:

    Q1 = clean_df[column].quantile(0.25)
    Q3 = clean_df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    clean_df[column] = clean_df[column].clip(
        lower=lower_bound,
        upper=upper_bound
    )

In [ ]:
outlier_summary_after = []

for column in feature_columns:

    Q1 = clean_df[column].quantile(0.25)
    Q3 = clean_df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = clean_df[
        (clean_df[column] < lower_bound)
        | (clean_df[column] > upper_bound)
    ]

    outlier_summary_after.append({
        "Feature": column,
        "Outlier Count": len(outliers)
    })

outlier_summary_after = pd.DataFrame(outlier_summary_after)

display(outlier_summary_after)

      Feature  Outlier Count
0   Feature_1              0
1   Feature_2              0
2   Feature_3              0
3   Feature_4              0
4   Feature_5              0
5   Feature_6              0
6   Feature_7              0
7   Feature_8              0
8   Feature_9              0
9  Feature_10              0

In [14]:
clean_df.to_csv("../data/clean_numeric_pattern.csv", index = False)