In [1]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv("../data/numeric_pattern.csv")
df.head()

,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Feature_10,Target
0,54.570756,30.683384,73.857248,34.463610,-0.997091,5.708020,436.241956,6.438559,37.043679,-2.726610,502.006478
1,34.400238,43.165021,81.274378,85.296915,-1.239023,78.902301,328.446838,1.893153,15.857470,-2.942670,190.572920
2,61.256768,55.429814,100.329841,48.929734,-0.297629,13.699700,427.330514,8.142972,22.236607,-1.654494,639.090183
3,64.108471,55.254794,107.078556,30.870235,0.709499,12.948322,370.239586,8.684036,16.674755,4.076734,680.857199
4,20.734472,4.186153,84.374899,23.631261,0.444786,8.482274,409.549934,9.226837,15.808623,-2.758592,519.100481

In [11]:
df.shape

(5075, 11)

In [12]:
df.head()

,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Feature_10,Target
0,54.570756,30.683384,73.857248,34.463610,-0.997091,5.708020,436.241956,6.438559,37.043679,-2.726610,502.006478
1,34.400238,43.165021,81.274378,85.296915,-1.239023,78.902301,328.446838,1.893153,15.857470,-2.942670,190.572920
2,61.256768,55.429814,100.329841,48.929734,-0.297629,13.699700,427.330514,8.142972,22.236607,-1.654494,639.090183
3,64.108471,55.254794,107.078556,30.870235,0.709499,12.948322,370.239586,8.684036,16.674755,4.076734,680.857199
4,20.734472,4.186153,84.374899,23.631261,0.444786,8.482274,409.549934,9.226837,15.808623,-2.758592,519.100481

In [13]:
df.tail()

,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Feature_10,Target
5070,54.843638,96.213520,86.616030,48.271756,-0.327501,0.520816,569.917209,5.943297,23.439348,3.753168,529.612301
5071,55.497971,28.689382,66.057668,72.870472,2.171383,19.424319,554.392486,1.099662,32.542701,4.336262,294.371249
5072,43.279059,77.767478,82.973241,75.509102,-0.518796,13.009168,587.877697,6.715139,19.837693,1.202207,496.056971
5073,37.793409,6.276328,149.767245,50.952910,-1.021670,14.683903,496.275763,5.559573,28.642410,-4.503973,461.888904
5074,56.028924,33.801483,74.193268,85.299339,-0.989034,7.748292,474.121361,3.118200,31.182315,-0.725834,306.683132

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5075 entries, 0 to 5074
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Feature_1   5075 non-null   float64
 1   Feature_2   5025 non-null   float64
 2   Feature_3   5075 non-null   float64
 3   Feature_4   5075 non-null   float64
 4   Feature_5   5024 non-null   float64
 5   Feature_6   5075 non-null   float64
 6   Feature_7   5075 non-null   float64
 7   Feature_8   5075 non-null   float64
 8   Feature_9   5025 non-null   float64
 9   Feature_10  5075 non-null   float64
 10  Target      5075 non-null   float64
dtypes: float64(11)
memory usage: 436.3 KB

In [16]:
df.describe()

,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Feature_10,Target
count,5075.000000,5025.000000,5075.000000,5075.000000,5024.000000,5075.000000,5075.000000,5075.000000,5025.000000,5075.000000,5075.000000
mean,50.082682,49.835981,99.878464,50.439699,0.026168,20.263281,502.555380,5.561813,24.924063,-0.001260,491.815622
std,16.958630,28.903240,24.966929,23.363927,0.990464,20.277758,112.162731,2.603951,4.980710,2.868526,138.152879
min,-4.726192,0.031442,2.804891,10.001539,-3.530409,0.002137,74.299071,1.005180,6.038711,-4.999379,139.768167
25%,39.666520,24.732327,83.132956,30.200264,-0.636573,5.925702,432.874662,3.291263,21.624099,-2.476544,387.873184
50%,50.029990,50.430488,99.432712,50.828308,0.021766,13.788264,499.784551,5.600615,24.919922,0.018243,476.165626
75%,59.545622,74.204975,116.656336,70.532882,0.675772,28.251397,569.075903,7.819349,28.287315,2.467005,591.354861
max,277.277361,99.997702,203.781035,89.964719,3.556363,187.205779,1876.030343,9.999182,50.036176,4.999937,922.108128

In [18]:
df.isnull().sum()

Feature_1      0
Feature_2     50
Feature_3      0
Feature_4      0
Feature_5     51
Feature_6      0
Feature_7      0
Feature_8      0
Feature_9     50
Feature_10     0
Target         0
dtype: int64