In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/BNPParibas_Data.csv")
df.head()

,customer_id,age,tenure_months,monthly_charges,total_charges,contract_type,internet_service,support_tickets,payment_method,churn
0,1,56,15,59.23,929.62,Month-to-Month,Fiber,5,UPI,1
1,2,69,64,24.20,1613.60,Month-to-Month,Fiber,1,Credit Card,1
2,3,46,28,78.02,2053.63,One Year,Fiber,1,UPI,0
3,4,32,39,45.95,1688.47,Month-to-Month,Fiber,1,UPI,0
4,5,60,57,49.88,2950.23,Month-to-Month,NaN,3,Bank Transfer,0

In [4]:
df.shape

(1000, 10)

In [5]:
df.head()

,customer_id,age,tenure_months,monthly_charges,total_charges,contract_type,internet_service,support_tickets,payment_method,churn
0,1,56,15,59.23,929.62,Month-to-Month,Fiber,5,UPI,1
1,2,69,64,24.20,1613.60,Month-to-Month,Fiber,1,Credit Card,1
2,3,46,28,78.02,2053.63,One Year,Fiber,1,UPI,0
3,4,32,39,45.95,1688.47,Month-to-Month,Fiber,1,UPI,0
4,5,60,57,49.88,2950.23,Month-to-Month,NaN,3,Bank Transfer,0

In [6]:
df.tail()

,customer_id,age,tenure_months,monthly_charges,total_charges,contract_type,internet_service,support_tickets,payment_method,churn
995,996,60,51,76.76,3585.64,Month-to-Month,DSL,2,Credit Card,1
996,997,64,15,106.28,1571.75,Month-to-Month,Fiber,2,Credit Card,1
997,998,62,68,111.18,7642.38,Month-to-Month,Fiber,1,Credit Card,1
998,999,35,21,106.95,2169.02,Month-to-Month,DSL,3,Credit Card,1
999,1000,55,13,28.82,391.18,Month-to-Month,DSL,1,Credit Card,0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       1000 non-null   int64
 1   age               1000 non-null   int64
 2   tenure_months     1000 non-null   int64
 3   monthly_charges   1000 non-null   float64
 4   total_charges     1000 non-null   float64
 5   contract_type     1000 non-null   object
 6   internet_service  911 non-null    object
 7   support_tickets   1000 non-null   int64
 8   payment_method    1000 non-null   object
 9   churn             1000 non-null   int64
dtypes: float64(2), int64(5), object(3)
memory usage: 78.2+ KB

In [8]:
df.describe()

,customer_id,age,tenure_months,monthly_charges,total_charges,support_tickets,churn
count,1000.000000,1000.00000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,43.81900,35.45900,79.967150,2800.235380,1.956000,0.502000
std,288.819436,14.99103,20.36819,40.071165,2300.029618,1.318257,0.500246
min,1.000000,18.00000,1.00000,10.220000,19.630000,0.000000,0.000000
25%,250.750000,31.00000,17.75000,46.040000,961.465000,1.000000,0.000000
50%,500.500000,44.00000,36.00000,80.870000,2106.430000,2.000000,1.000000
75%,750.250000,56.00000,53.00000,114.062500,4110.717500,3.000000,1.000000
max,1000.000000,69.00000,71.00000,149.770000,10772.520000,8.000000,1.000000

In [9]:
df.isnull().sum()

customer_id          0
age                  0
tenure_months        0
monthly_charges      0
total_charges        0
contract_type        0
internet_service    89
support_tickets      0
payment_method       0
churn                0
dtype: int64