In [4]:
!pip install faker

Collecting faker
  Downloading faker-40.37.0-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 934.5 kB/s eta 0:00:00:0100:010m
Installing collected packages: faker
Successfully installed faker-40.37.0

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [3]:
!pip install pandas

Collecting pandas
  Using cached pandas-2.3.3-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.8 MB)
Collecting pytz>=2020.1
  Using cached pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
Requirement already satisfied: numpy>=1.22.4 in /home/adithya/Documents/Padhai/Code/bridge_labz/NumericPatternAssessment/venv/lib/python3.10/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/adithya/Documents/Padhai/Code/bridge_labz/NumericPatternAssessment/venv/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Collecting tzdata>=2022.7
  Using cached tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Requirement already satisfied: six>=1.5 in /home/adithya/Documents/Padhai/Code/bridge_labz/NumericPatternAssessment/venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.3.3 pytz-2026.3.post1 tzdata-2026.3

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [2]:
!pip install numpy

Requirement already satisfied: numpy in /home/adithya/Documents/Padhai/Code/bridge_labz/NumericPatternAssessment/venv/lib/python3.10/site-packages (2.2.6)

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [5]:
import numpy as np
import pandas as pd
from faker import Faker

In [6]:
SEED = 42
N_SAMPLES = 5000

fake = Faker()
Faker.seed(SEED)

rng = np.random.default_rng(SEED)

In [7]:
record_ids = [
    fake.uuid4()
    for _ in range(N_SAMPLES)
]

In [8]:
df = pd.DataFrame({
    "record_id": record_ids,

    "Feature_1": rng.normal(
        loc=50,
        scale=15,
        size=N_SAMPLES
    ),

    "Feature_2": rng.uniform(
        low=0,
        high=100,
        size=N_SAMPLES
    ),

    "Feature_3": rng.normal(
        loc=100,
        scale=25,
        size=N_SAMPLES
    ),

    "Feature_4": rng.uniform(
        low=10,
        high=90,
        size=N_SAMPLES
    ),

    "Feature_5": rng.normal(
        loc=0,
        scale=1,
        size=N_SAMPLES
    ),

    "Feature_6": rng.exponential(
        scale=20,
        size=N_SAMPLES
    ),

    "Feature_7": rng.normal(
        loc=500,
        scale=100,
        size=N_SAMPLES
    ),

    "Feature_8": rng.uniform(
        low=1,
        high=10,
        size=N_SAMPLES
    ),

    "Feature_9": rng.normal(
        loc=25,
        scale=5,
        size=N_SAMPLES
    ),

    "Feature_10": rng.uniform(
        low=-5,
        high=5,
        size=N_SAMPLES
    )
})

In [9]:
noise = rng.normal(
    loc=0,
    scale=12,
    size=N_SAMPLES
)


df["Target"] = (
    2.8 * df["Feature_1"]
    + 0.9 * df["Feature_2"]
    + 1.5 * df["Feature_3"]
    - 1.2 * df["Feature_4"]
    + 8.0 * df["Feature_5"]
    + 0.035 * df["Feature_7"]

    # Non-linear relationship
    + 4.0 * np.square(df["Feature_8"])

    + 2.0 * df["Feature_9"]

    # Another non-linear relationship
    + 5.0 * np.sin(df["Feature_10"])

    + noise
)

In [10]:
df.head()

,record_id,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Feature_10,Target
0,bdd640fb-0667-4ad1-9c80-317fa3b1799d,54.570756,30.683384,73.857248,34.463610,-0.997091,5.708020,436.241956,6.438559,37.043679,-2.726610,502.006478
1,23b8c1e9-3924-46de-beb1-3b9046685257,34.400238,43.165021,81.274378,85.296915,-1.239023,78.902301,328.446838,1.893153,15.857470,-2.942670,190.572920
2,bd9c66b3-ad3c-4d6d-9a3d-1fa7bc8960a9,61.256768,55.429814,100.329841,48.929734,-0.297629,13.699700,427.330514,8.142972,22.236607,-1.654494,639.090183
3,972a8469-1641-4f82-8b9d-2434e465e150,64.108471,55.254794,107.078556,30.870235,0.709499,12.948322,370.239586,8.684036,16.674755,4.076734,680.857199
4,17fc695a-07a0-4a6e-8822-e8f36c031199,20.734472,4.186153,84.374899,23.631261,0.444786,8.482274,409.549934,9.226837,15.808623,-2.758592,519.100481

In [ ]:
# null values
for column in [
    "Feature_2",
    "Feature_5",
    "Feature_9"
]:

    missing_indices = rng.choice(
        df.index,
        size=int(N_SAMPLES * 0.01),
        replace=False
    )

    df.loc[
        missing_indices,
        column
    ] = np.nan

In [ ]:
# Duplicate values
duplicates = df.sample(
    n=25,
    random_state=SEED
)

df = pd.concat(
    [df, duplicates],
    ignore_index=True
)

,record_id,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Feature_10,Target
0,bdd640fb-0667-4ad1-9c80-317fa3b1799d,54.570756,30.683384,73.857248,34.463610,-0.997091,5.708020,436.241956,6.438559,37.043679,-2.726610,502.006478
1,23b8c1e9-3924-46de-beb1-3b9046685257,34.400238,43.165021,81.274378,85.296915,-1.239023,78.902301,328.446838,1.893153,15.857470,-2.942670,190.572920
2,bd9c66b3-ad3c-4d6d-9a3d-1fa7bc8960a9,61.256768,55.429814,100.329841,48.929734,-0.297629,13.699700,427.330514,8.142972,22.236607,-1.654494,639.090183
3,972a8469-1641-4f82-8b9d-2434e465e150,64.108471,55.254794,107.078556,30.870235,0.709499,12.948322,370.239586,8.684036,16.674755,4.076734,680.857199
4,17fc695a-07a0-4a6e-8822-e8f36c031199,20.734472,4.186153,84.374899,23.631261,0.444786,8.482274,409.549934,9.226837,15.808623,-2.758592,519.100481
...,...,...,...,...,...,...,...,...,...,...,...,...
5070,e879c9a6-0ae9-4acc-b1c9-66b39eb03954,54.843638,96.213520,86.616030,48.271756,-0.327501,0.520816,569.917209,5.943297,23.439348,3.753168,529.612301
5071,5efa9c5b-7421-4f46-a37e-4b0122bae10e,55.497971,28.689382,66.057668,72.870472,2.171383,19.424319,554.392486,1.099662,32.542701,4.336262,294.371249
5072,24ce1460-ef5a-4491-953d-165346641858,43.279059,77.767478,82.973241,75.509102,-0.518796,13.009168,587.877697,6.715139,19.837693,1.202207,496.056971
5073,ce177b4e-0837-48a3-9261-a7ab3aa2e4f9,37.793409,6.276328,149.767245,50.952910,-1.021670,14.683903,496.275763,5.559573,28.642410,-4.503973,461.888904
5074,23966b83-5cd1-4b22-b0e8-b2fa4fc34759,56.028924,33.801483,74.193268,85.299339,-0.989034,7.748292,474.121361,3.118200,31.182315,-0.725834,306.683132

In [ ]:
# Outliers
outlier_indices = rng.choice(
    df.index,
    size=10,
    replace=False
)

df.loc[
    outlier_indices,
    "Feature_1"
] *= 5

df.loc[
    outlier_indices,
    "Feature_7"
] *= 3

In [19]:
df = df.drop(
    columns=["record_id"]
)

In [20]:
df.head()

,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Feature_10,Target
0,54.570756,30.683384,73.857248,34.463610,-0.997091,5.708020,436.241956,6.438559,37.043679,-2.726610,502.006478
1,34.400238,43.165021,81.274378,85.296915,-1.239023,78.902301,328.446838,1.893153,15.857470,-2.942670,190.572920
2,61.256768,55.429814,100.329841,48.929734,-0.297629,13.699700,427.330514,8.142972,22.236607,-1.654494,639.090183
3,64.108471,55.254794,107.078556,30.870235,0.709499,12.948322,370.239586,8.684036,16.674755,4.076734,680.857199
4,20.734472,4.186153,84.374899,23.631261,0.444786,8.482274,409.549934,9.226837,15.808623,-2.758592,519.100481

In [21]:
df.to_csv("../data/numeric_pattern.csv")