In [2]:
!pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.7.2-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (9.7 MB)
Collecting joblib>=1.2.0
  Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Collecting threadpoolctl>=3.1.0
  Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Collecting scipy>=1.8.0
  Using cached scipy-1.15.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.7 MB)
Requirement already satisfied: numpy>=1.22.0 in /home/adithya/Documents/Padhai/Code/bridge_labz/NumericPatternAssessment/venv/lib/python3.10/site-packages (from scikit-learn) (2.2.6)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.5.3 scikit-learn-1.7.2 scipy-1.15.3 threadpoolctl-3.6.0

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [5]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import pandas as pd

In [ ]:
clean_df = pd.read_csv("../data/clean_numeric_pattern.csv")

# Features
X = clean_df.drop(columns=["Target"])

# Target
y = clean_df["Target"]

In [ ]:
# Standard scaler

standard_scaler = StandardScaler()

X_standard = standard_scaler.fit_transform(X)

In [ ]:
X_standard_df = pd.DataFrame(
    X_standard,
    columns=X.columns,
    index=X.index
)

X_standard_df.to_csv("../data/standard_scaler.csv")
display(X_standard_df.head())

,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Feature_10
0,0.319567,-0.668816,-1.048922,-0.679157,-1.044875,-0.792821,-0.645970,0.336214,2.471741,-0.949097
1,-1.026259,-0.234241,-0.749968,1.495702,-1.291910,2.482942,-1.722355,-1.408037,-1.849467,-1.024409
2,0.765673,0.192783,0.018079,-0.060236,-0.330657,-0.326842,-0.734955,0.990264,-0.548357,-0.575387
3,0.955946,0.186690,0.290092,-0.832897,0.697717,-0.370653,-1.305035,1.197892,-1.682771,1.422360
4,-1.938071,-1.591373,-0.624999,-1.142610,0.427419,-0.631060,-0.912502,1.406186,-1.859430,-0.960245

In [11]:
print("Means after StandardScaler:")
display(X_standard_df.mean())

print("\nStandard deviations after StandardScaler:")
display(X_standard_df.std())

Means after StandardScaler:

Feature_1    -1.037185e-16
Feature_2     1.648130e-16
Feature_3    -1.449217e-16
Feature_4    -1.094017e-16
Feature_5     1.989122e-17
Feature_6     3.267843e-17
Feature_7     2.220002e-16
Feature_8     1.877234e-16
Feature_9    -3.026307e-16
Feature_10    4.688644e-17
dtype: float64

Standard deviations after StandardScaler:

Feature_1     1.0001
Feature_2     1.0001
Feature_3     1.0001
Feature_4     1.0001
Feature_5     1.0001
Feature_6     1.0001
Feature_7     1.0001
Feature_8     1.0001
Feature_9     1.0001
Feature_10    1.0001
dtype: float64

In [12]:
# Min Max Scaler

minmax_scaler = MinMaxScaler()

X_minmax = minmax_scaler.fit_transform(X)

In [14]:
X_minmax_df = pd.DataFrame(
    X_minmax,
    columns=X.columns,
    index=X.index
)

X_minmax_df.to_csv("../data/minmax_scaler.csv",)

display(X_minmax_df.head())

,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Feature_10
0,0.562739,0.306623,0.305761,0.305917,0.304013,0.092200,0.381263,0.604111,0.959750,0.227292
1,0.309029,0.431481,0.361091,0.941626,0.257217,1.000000,0.182366,0.098729,0.154763,0.205685
2,0.646837,0.554171,0.503242,0.486827,0.439308,0.221335,0.364820,0.793617,0.397144,0.334511
3,0.682707,0.552420,0.553586,0.260979,0.634114,0.209193,0.259479,0.853775,0.185816,0.907673
4,0.137138,0.041561,0.384221,0.170450,0.582911,0.137028,0.332013,0.914127,0.152907,0.224094

In [15]:
print("Minimum values:")
display(X_minmax_df.min())

print("\nMaximum values:")
display(X_minmax_df.max())

Minimum values:

Feature_1     0.0
Feature_2     0.0
Feature_3     0.0
Feature_4     0.0
Feature_5     0.0
Feature_6     0.0
Feature_7     0.0
Feature_8     0.0
Feature_9     0.0
Feature_10    0.0
dtype: float64

Maximum values:

Feature_1     1.0
Feature_2     1.0
Feature_3     1.0
Feature_4     1.0
Feature_5     1.0
Feature_6     1.0
Feature_7     1.0
Feature_8     1.0
Feature_9     1.0
Feature_10    1.0
dtype: float64